# Generated by Django 2.2.7 on 2019-11-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('A_pos', models.IntegerField()),
                ('A_neg', models.IntegerField()),
                ('B_pos', models.IntegerField()),
                ('B_neg', models.IntegerField()),
                ('O_pos', models.IntegerField()),
                ('O_neg', models.IntegerField()),
                ('AB_pos', models.IntegerField()),
                ('AB_neg', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
