# Generated by Django 2.2.7 on 2019-11-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20191117_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='username',
            new_name='owner',
        ),
    ]
