# Generated by Django 2.2.7 on 2019-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20191117_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='city',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
